// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_ChuqvM4nnWPo-khkzocprxWKpRdF44s',
    appId: '1:214079395019:web:c2a21e2f543836a450b74e',
    messagingSenderId: '214079395019',
    projectId: 'teklif-36a44',
    authDomain: 'teklif-36a44.firebaseapp.com',
    storageBucket: 'teklif-36a44.appspot.com',
    measurementId: 'G-6TY8G388M6',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOIfPht0UDWGclR8m_teXN9k94SRbeny0',
    appId: '1:214079395019:ios:b3dead193ad4d07650b74e',
    messagingSenderId: '214079395019',
    projectId: 'teklif-36a44',
    storageBucket: 'teklif-36a44.appspot.com',
    iosBundleId: 'com.teklif.teklif',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOIfPht0UDWGclR8m_teXN9k94SRbeny0',
    appId: '1:214079395019:ios:b3dead193ad4d07650b74e',
    messagingSenderId: '214079395019',
    projectId: 'teklif-36a44',
    storageBucket: 'teklif-36a44.appspot.com',
    iosBundleId: 'com.teklif.teklif',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_ChuqvM4nnWPo-khkzocprxWKpRdF44s',
    appId: '1:214079395019:web:81b3e7ad8157df2d50b74e',
    messagingSenderId: '214079395019',
    projectId: 'teklif-36a44',
    authDomain: 'teklif-36a44.firebaseapp.com',
    storageBucket: 'teklif-36a44.appspot.com',
    measurementId: 'G-ECFJK7196H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6BwjZFe3twHV1B1w-p3HE1WQf3MYB8Fc',
    appId: '1:214079395019:android:bb0d2471bb32fab850b74e',
    messagingSenderId: '214079395019',
    projectId: 'teklif-36a44',
    storageBucket: 'teklif-36a44.appspot.com',
  );

}